#!/bin/sh

set -e

TYPE=$1
REPO=$TYPE
case $TYPE in base) REPO=src;; esac

cd $HOME/git_conv
LOG="$PWD/`date +%Y-%m-%d`_${TYPE}.log"

(git pull && cd svn2git && make) >> $LOG 2>&1

./svnmir.sh -1

case "$1" in
    base)
	rm -rf freebsd-$1.git/ gitlog-freebsd-$1.git log-freebsd-$1.git log-freebsd-$1.git.old log-$1
	rm -rf mi
	rm -rf archive/*/wrk 2>/dev/null
	./git_conv "$@" >> $LOG 2>&1
	./tag_archived_src.sh >> $LOG 2>&1
	./fix_bogus_tags.sh >> $LOG 2>&1
        ;;
    ports|doc)
	rm -rf freebsd-$1.git/ gitlog-freebsd-$1.git log-freebsd-$1.git log-freebsd-$1.git.old log-$1
	./git_conv "$@" >> $LOG 2>&1
        ;;
    *)
        echo "Need to specify which repo to convert" >&2
        exit 1
        ;;
esac

if [ $? != 0 ]; then
    echo "Error during git_conv" >&2
    tail -30 $LOG
    exit 1
else
    cd freebsd-$1.git && git push -q freebsd
    #&& cd $HOME/repositories/$REPO.git && git gc --aggressive --prune=now --force --quiet
fi
