#!/bin/sh

set -e

TYPE=$1
REPO=$TYPE
case $TYPE in base) REPO=src;; esac
: ${GIT_USER:=git}

case "$1" in
    base|ports|doc)
	;;
    *)
	echo "Need to specify which repo to convert" >&2
	exit 1
	;;
esac

test `whoami` = $GIT_USER && cd $HOME/git_conv && ./svnmir.sh -1

LOG="$PWD/`date +%Y-%m-%d`_${TYPE}.log"
git pull >> $LOG 2>&1
(cd svn2git && make) >> $LOG 2>&1
(cd parsecvs && make) >> $LOG 2>&1

case "$1" in
    base)
	test -d freebsd-$1.git && find freebsd-$1.git -not -path "*/objects*" -type f -delete
	rm -rf gitlog-freebsd-$1.git log-freebsd-$1.git log-freebsd-$1.git.old log-$1
	rm -rf mi
	rm -rf archive/*/wrk 2>/dev/null
	./git_conv "$@" >> $LOG 2>&1
	./tag_archived_src.sh >> $LOG 2>&1
	./fix_bogus_tags.sh >> $LOG 2>&1
	(cd freebsd-$1.git && git gc --prune=now >> $LOG 2>&1)
        ;;
    ports|doc)
	test -d freebsd-$1.git && find freebsd-$1.git -not -path "*/objects*" -type f -delete || true
	rm -rf gitlog-freebsd-$1.git log-freebsd-$1.git log-freebsd-$1.git.old log-$1
	./git_conv "$@" >> $LOG 2>&1
        ;;
esac

if [ $? != 0 ]; then
    echo "Error during git_conv" >&2
    tail -30 $LOG
    exit 1
else
    # guard against me messing this up ...
    test `whoami` = $GIT_USER && cd freebsd-$1.git && git push -q freebsd
    #&& cd $HOME/repositories/$REPO.git && git gc --aggressive --prune=now --force --quiet
fi
